// Made by Luis Plasencia Pulido


#include "Interaction/CombatInterface.h"

// Add default functionality here for any ICombatInterface functions that are not pure virtual.
// As we changed getPlayerLevel to blueprint native event, this deffinition is not valid (redefinition)
// The actual definition will be auto generated by the unreal header tool when it seed the blueprintnativeevent macro specifier
//int32 ICombatInterface::GetPlayerLevel()
//{
//	return 0;
//}

